### ISSUE TITLE
The repository is missing examples on CORS and CSRF

### ISSUE THREAD

**Issue by wsierakowski** [PacktPublishing/Hands-on-Spring-Security-5.1.1#1]
The last section of the course focuses on the CSRF and CORS based on the code for travel booking API. It seems that this code example is missing here in this repository. I think it would be really useful if it was made available as well to better understand these examples.

**Comment by PacktDwayne** [comment]
Hello Woj Sierak.

Apologies for the delayed response. We've asked the author to update the repository as soon as possible. You should get an update on this thread once that's done.

Thank you so much for your patience. Have a nice day.

Regards,
Dwayne.

**Comment by PacktDwayne** [comment]
Hello Woj,

The CORS example has been added here: https://github.com/PacktPublishing/Hands-on-Spring-Security-5.1.1/tree/master/CORS
